Adding a few Picard basecalling tasks.
fulcrumgenomics/dagr pull request #277
Opened 2017-04-07 19:52 UTC by nh13

2017-04-07 21:08 UTC, nh13 commented
@tfenne see 8e4ae73 for a travis-ci build issue fix.  Basically, the tests were using too much memory in the container environment (exit 137 from docker is a SIGKILL).

2017-04-10 18:28 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/IlluminaBasecallsToSam.scala
> +  }
I am not convinced this is the right strategy.  I have seen many cases where we have A LOT more memory per core than 1G and it still wont succeed.  I am tempted to implement something that will increase the memory per core, as well as reducing the # of cores.

2017-04-10 20:04 UTC, tfenne requested changes
A few oddball choices perhaps informed by a single use-case, but otherwise looks ok.

2017-04-10 20:04 UTC, tfenne commented on tasks/src/main/scala/dagr/tasks/picard/CollectIlluminaBasecallingMetrics.scala
> +  def toMetricsFileName(lane: Int): String = s".lane-$lane.metrics"
toMetricsExtension?

2017-04-10 20:04 UTC, tfenne commented on tasks/src/main/scala/dagr/tasks/picard/CollectIlluminaBasecallingMetrics.scala
> +  override def in: FilePath = outputDir.getOrElse(basecallsDir).resolve("basecalling")
This is bizarre.  Why would we prefer the output directory as the input directory?

2017-04-10 20:04 UTC, tfenne commented on tasks/src/main/scala/dagr/tasks/picard/CollectIlluminaLaneMetrics.scala
> +                                 basecallsDir: DirPath,
Shouldn't this just be called `output`?

2017-04-10 20:04 UTC, tfenne commented on tasks/src/main/scala/dagr/tasks/picard/ExtractIlluminaBarcodes.scala
> +                              barcodesDir: Option[DirPath] = None
Again, I think this should be `output` because that's the name of the Picard parameter, and it really is just controlling where the output is going.

2017-04-10 20:04 UTC, tfenne commented on tasks/src/main/scala/dagr/tasks/picard/IlluminaBasecallsToSam.scala
> +                             adapterPairs: Seq[IlluminaAdapterPair] = Seq(
This seems an odd choice.  I'd either pick a more sensible default set, or leave the tool to decide the defaults.

2017-04-10 20:57 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/IlluminaBasecallsToSam.scala
> +  }
Solved in an upcoming commit; discussed with you.

2017-04-10 21:03 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/CollectIlluminaBasecallingMetrics.scala
> +  override def in: FilePath = outputDir.getOrElse(basecallsDir).resolve("basecalling")
Good point, it _was_ to be able to set the output metrics file correctly, which is based on the input file name.  I could override the `PicardMetricsTask.pathPrefix` method, but instead I'll put a large comment here.

2017-04-10 21:10 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/CollectIlluminaBasecallingMetrics.scala
> +  override def in: FilePath = outputDir.getOrElse(basecallsDir).resolve("basecalling")
Actually, I think I can have a parameter `prefix: Option[Path]` and then it will make more sense.  I'll comment this well in the code.

2017-04-10 21:14 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/IlluminaBasecallsToSam.scala
> +                             adapterPairs: Seq[IlluminaAdapterPair] = Seq(
```
    @Option(doc = "Which adapters to look for in the read.")
    public List<IlluminaAdapterPair> ADAPTERS_TO_CHECK = new ArrayList<IlluminaAdapterPair>(
            Arrays.asList(IlluminaAdapterPair.INDEXED,
                    IlluminaAdapterPair.DUAL_INDEXED,
                    IlluminaAdapterPair.NEXTERA_V2,
                    IlluminaAdapterPair.FLUIDIGM));
```

https://github.com/broadinstitute/picard/blob/9f41e06267010c975a5e96913ab56a101f0f2b9f/src/main/java/picard/illumina/IlluminaBasecallsToSam.java#L198-L202

![](http://www.reactiongifs.com/wp-content/uploads/2013/10/tim-and-eric-mind-blown.gif)

2017-04-10 21:16 UTC, nh13 commented
@tfenne I fixed up the `CollectIlluminaBasecallingMetrics`, improved `IlluminaBasecallsToSam` based on discussion, and fixed all but the default adapters to check (which are the ones in Picard).  Back to you.

2017-04-11 11:40 UTC, tfenne commented on tasks/src/main/scala/dagr/tasks/picard/CollectIlluminaLaneMetrics.scala
> +  * is provided with either, an error will be thrown.
What is the preferred solution?  To convert those operators to template?

2017-04-11 11:40 UTC, tfenne commented on tasks/src/main/scala/dagr/tasks/picard/ExtractIlluminaBarcodes.scala
> +  override def in: FilePath = _barcodesDir.resolve("barcode_counts")
Could you add a similar comment here please about overriding `in` to make `metricsFile` do the right thing?  Relatedly is this actually simpler than just in `addPicardArgs` writing:
 `buffer += "METRICS_FILE=" + _barcodesDir.resolve("barcode_counts") + metricsExtension`?

2017-04-11 11:40 UTC, tfenne commented on tasks/src/main/scala/dagr/tasks/picard/IlluminaBasecallsToSam.scala
> +  override def retry(systemResources: SystemResources, taskInfo: TaskExecutionInfo): Boolean = {
I wonder if you should mix in one or more of the OOM traits so that this retry only happens if an OOM was detected and not some other kind of error?

2017-04-11 16:17 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/ExtractIlluminaBarcodes.scala
> +  override def in: FilePath = _barcodesDir.resolve("barcode_counts")
It's really to make it play nice with the `PicardMetricsTask`. I will update it to the same behavior.

2017-04-11 16:32 UTC, nh13 commented
@tfenne one last look before I merge?

2017-04-12 20:46 UTC, merged