Add Picard BuildBamIndex to dagr tasks
fulcrumgenomics/dagr pull request #344
Opened 2019-05-12 08:41 UTC by clintval

Surprised to find this little one didn't already exist!

2019-05-13 18:32 UTC, nh13 requested changes
@clintval it _**is**_ curious as to why we haven't needed this.  Most tools that produce BAM (in coordinate sorted output order), can produce them while indexing on the fly.  This removes the need to write the output BAM then read it again.  Do you have a use-case where the tool does not do that?  

Off the top of my head, if you have a tool that produces SAM, you could have it produce SAM or uncompressed BAM, then write a quick tool to which you pipe in the previous output, and the latter tool indexes and compresses it to the output.  This would make any tool that produces SAM/BAM be able to "index on the fly", as the compression/decompression is performed only once.  It also sort-of acts as asynchronous IO.  You can even have the tool sort the output data, so the SAM producing tool doesn't need to sort it.  It sound like you can just use `fgbio`'s `SortBam` or `sambamba sort`, for the latter, and some "view" tool if you don't need sorting.  `</digression>`

2019-05-13 18:32 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/BuildBamIndex.scala
> +    out.foreach(bai => buffer.append("O=" + bai.toString))
Why not?
```suggestion
    out.foreach(bai => buffer.append("O=" + bai. toAbsolutePath))
```

2019-05-14 04:07 UTC, clintval commented
@nh13 Ha I'm very much with you, but I'm working with a design decision that is not my doing.

This command will produce the following directory structure:

```bash
❯ mkdir output
❯ STAR \
	--runThreadN 6 \
	--runMode alignReads \
	--readFilesIn read1.fq read2.fq \
	--genomeDir /pipeline/references-star/hg38-100n \
	--outFileNamePrefix output/sample.library \
	--outSAMtype BAM SortedByCoordinate
```

```
❯ \ls -1 output
sample.library.Aligned.sortedByCoord.out.bam
sample.library.Log.final.out
sample.library.Log.out
sample.library.Log.progress.out
sample.library.SJ.out.tab
```

`STAR`, to the best of my knowledge, does not allow piping the alignments since `STAR` builds its own file handles internally. The best I can do is provide an output path prefix and index the BAM _after_.

Granted, I could ask `STAR` to output unsorted plaintext SAM and then perform the sort and write to binary, but that seems like a lot of writing to disk and I'd rather just skim/read the final BAM and index with a Picard tool.

2019-05-14 04:11 UTC, clintval commented
Because the BAM files `STAR` produces are also spec-non-conforming by having no read groups, I've had to find other ways of fixing the file!

https://github.com/clintval/cvbio/blob/225946afb62bf16959ef4fe4d8e37ba07cc365d5/pipelines/src/main/scala/com/cvbio/pipeline/pipelines/StarAlignPipeline.scala#L62-L78

To be honest, I no longer truly need the `BuildBamIndex` task... but I implemented it on my way to another better method and thought it would still be a nice contribution.

I see plenty of third-party with additional `samtools index` operations and I'm not sure why exactly. I personally enjoy not having to install samtools (a second dependency) when I can do just fine with a single JAR and the base Picard routines.

2019-05-14 04:47 UTC, merged