Add the Picard task AddOrReplaceReadGroups
fulcrumgenomics/dagr pull request #346
Opened 2019-05-12 21:07 UTC by clintval

2019-05-12 21:09 UTC, clintval commented on tasks/src/main/scala/dagr/tasks/picard/AddOrReplaceReadGroups.scala
> +  val platformModel: Option[String] = None
The fields are ordered as they are on the Picard CLI which puts two optionals (`sortOrder` and `id` before required fields.

Would you like the constructor fields sorted "required -> optional"?

2019-05-13 17:01 UTC, clintval commented on tasks/src/main/scala/dagr/tasks/picard/AddOrReplaceReadGroups.scala
> +  val DefaultLibraryId: String = "1"
https://github.com/broadinstitute/picard/blob/b02e42e0ca82efae70ee572766cbe101b6a2305e/src/main/java/picard/sam/AddOrReplaceReadGroups.java#L105-L106

2019-05-13 17:02 UTC, clintval commented on tasks/src/main/scala/dagr/tasks/picard/AddOrReplaceReadGroups.scala
> +  val platformModel: Option[String] = None
I just re-ordered "require -> optional". The API is better IMHO.

2019-05-13 18:46 UTC, nh13 requested changes
One minor nit about the default value for `id`.  Thanks for adding this.

2019-05-13 18:46 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/AddOrReplaceReadGroups.scala
> +  /** The Picard default for the Library ID tag. */
```suggestion
  /** The default for the Library ID tag in Picard's `AddOrReplaceReadGroups` tool. */
```

2019-05-13 18:46 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/AddOrReplaceReadGroups.scala
> +  val DefaultLibraryId: String = "1"
![serious](https://user-images.githubusercontent.com/846274/57645886-2346a800-7574-11e9-99da-32e48bd1f164.gif)

2019-05-13 18:46 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/AddOrReplaceReadGroups.scala
> +  val id: Option[String] = Some(AddOrReplaceReadGroups.DefaultLibraryId),
can't this just be `None`, and then we can rely upon Picard to set the default?

2019-05-13 18:46 UTC, nh13 commented on tasks/src/main/scala/dagr/tasks/picard/AddOrReplaceReadGroups.scala
> +    buffer.append("RGPL=" + platform)
Don't change this, but as a note that `platform` has only a fixed set of spec-compliant values.

2019-05-13 19:55 UTC, clintval commented on tasks/src/main/scala/dagr/tasks/picard/AddOrReplaceReadGroups.scala
> +  val DefaultLibraryId: String = "1"
I simply removed, I actually don't understand my original motivation anymore.

2019-05-14 04:48 UTC, merged