Optionally check configureExecutable config value path actually exists
fulcrumgenomics/dagr pull request #348
Opened 2019-05-17 05:47 UTC by clintval

I have a use case which is not supported by Dagr's current methods for executable configuration.

I want to configure a default location where executables can be placed such that Dagr always use them. If the executables do not exist on disk, then I want Dagr to fallback onto the system path.

With this PR, two alternate behaviors can be allowed without changing Dagr configuration and this will make it easier for me to share Dagr pipelines:

1. To get up and running very quickly, install dependencies with this command:

    ```bash
    ❯ conda install vcfanno
    ```

	Then execute the pipeline:

    ```bash
    ❯ java -jar pipeline.jar RunMe
    ```

2. To use a specific version of the pipeline dependencies or to use a different version than provided on your system path, simply place the executables at the following location:

    ```bash
    ❯ ls /pipeline/packages/
	/pipeline/packages/vcfanno 
    ```

	Then execute the pipeline:

    ```bash
    ❯ java -jar pipeline.jar RunMe
    ```

I'm not thrilled about providing the argument `mustExist`, would you rather this logic be allowed through a new function? Open to suggestions!

2019-05-21 23:58 UTC, nh13 requested changes
Minor changes, but I could also use @tfenne's input.  I think it may be time to move dagr out from using it's own `Configuration` class and use the [commons Configuration class](https://github.com/fulcrumgenomics/commons/blob/master/src/main/scala/com/fulcrumgenomics/commons/util/ConfigurationLike.scala).  If we do the latter, we could either add some of the missing methods directly (ex. `configureExecutable`) to the commons Configuration class, or extend it to a new trait/class (for things that want to configure executables) and put that there.

Regardless, I think this PR is fine (once comments have been addressed) and we can choose to do the migration later. @tfenne thoughts?

2019-05-21 23:58 UTC, nh13 commented on core/src/main/scala/dagr/core/config/Configuration.scala
> +    * @param mustExist ensure the configuration path to look up references a file which exists
```suggestion
    * @param allowMissingConfigReference true to require that the executable path in the configuration must exist, false fallback to the system path if the configuration path exists but not the returned executable path.
```
I don't _really_ like longer names, but in this case I asked "what must exist?" prior to reading the docs, so what do think about a longer name?  Also, I tried to be more verbose about the behavior, but feel free to wordsmith further.

2019-05-21 23:58 UTC, nh13 commented on core/src/main/scala/dagr/core/config/Configuration.scala
> +  def configureExecutable(path: String, executable: String, mustExist: Boolean = false) : Path = {
```suggestion
  def configureExecutable(path: String, executable: String, allowMissingConfigReference: Boolean = false) : Path = {
```

2019-05-21 23:58 UTC, nh13 commented on core/src/main/scala/dagr/core/config/Configuration.scala
> +      .filterNot(mustExist && !Files.exists(_))
```suggestion
      .filter(!allowMissingConfigReference || Files.exists(_))
```

2019-05-21 23:58 UTC, nh13 commented on core/src/main/scala/dagr/core/config/Configuration.scala
> +          + s" and executable '$executable' is not in the system path."
I think this statement isn't true for `allowMissingConfigReference=false`

2019-05-22 05:22 UTC, clintval commented
I did my best wordsmithing although I feel like improvements could still be made. A re-review would be great! I agree `allowMissingConfigReference` is clearer than `mustExist` but I'm not sure `missing` is the right verb and that `ConfigReference` is the right noun. For lack of a better idea, it rests.

The parameter rename raises a few API design questions for me that might be useful context for when we eventually move to `commons.util.Configuration`.

- Why do we want to allow for a missing executable at all?
- In the default case, do we expect the user to assert the executable exists after looking it up in the config since they will have no context as to if the executable path was found either in the config (uncertain executable existence) or on the system path (certain executable existence)?

2019-05-28 17:50 UTC, tfenne commented
I'm not entirely sure how I feel about this PR to be completely honest.  My main concern is that a mistake in config could lead to totally unexpected consequences.  E.g. I frequently have multiple versions of bwa on my system, and one of them lives on my default PATH.  If I add to config something like `bwa.executable=/packages/bwa-0.7.13/bni/bwa`, and expect pipeline will run bwa 0.7.13, I'd be unpleasantly surprised to find a) my pipelines didn't fail and b) they ran whatever version of bwa is on my system path.  That fear could be at least partly allayed by making the default behaviour to throw an error if a configured executable doesn't exist, but that means that any usages of `configureExecutable` inside of dagr wouldn't function how you'd want them.

Re: the name of `allowMissingConfigReference`, I think this is really hard to do without making it very wordy - since there are two things that could be missing; the config key could be undefined, or it's value could point to a nonexistent executable/file.  Here are a few options for (IMO) better names (with defaults that match the existing dagr behaviour):

* `configuredExecutablesMustExist: Boolean = true`
* `alwaysFallBackToSystemPath: Boolean = false`
* `allowConfiguredExecutablesToNotExist: Boolean = false`

2019-05-28 19:29 UTC, clintval commented
@tfenne, I understand your concern. Activating the feature in this PR would open you up to system path fallbacks if you included typos in your Dagr configuration.

Ultimately, I'm looking for a way to configure a Dagr pipeline using hard-coded paths as default, but permitting a system path search as a fallback if the executable is missing so I can leverage alternate dependencies that are installed using a package/environment manager like conda. This would allow me greater ease in end-to-end testing over a variety of tool dependency versions using the same Dagr pipelines (same release, same JAR).

I usually run Dagr pipelines on blank cloud instances so multiple system binaries risk is small for me but I also understand these pipelines run just as well on personal environments.

Is this PR blocked from your perspective?

Happy to keep chipping away at this feature if it's a desired addition!

2019-05-28 22:00 UTC, nh13 commented
@clintval why not have an empty dagr config, then use the system path to express priority order searching for binaries?

2019-05-28 22:52 UTC, nh13 commented
@tfenne @clintval  we could also implement the fallback as a global variable within `Configuration` that one could toggle.  Be default, it fails if the executable provided by the config path does not exist.  See https://github.com/fulcrumgenomics/dagr/pull/350

2019-05-29 00:00 UTC, clintval commented
Good suggestions all around. I'm 👍 on #350.

2021-01-24 04:18 UTC, closed without merging